services:

  db:
    container_name: postgresql
    image: postgres:14
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-postgres_db}
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      PGDATA: /data/postgres
    env_file:
      - .env
    volumes:
      - data:/data/postgres
    restart: always
    ports:
      - ${DATABASE_PORT:-5432}:5432

volumes:
  data: